@startuml
title Fonctionnalité 9 - Déplacement aléatoire des monstres

actor Timer
participant "gestionnaireMonstres:gestionnaireMonstres" as GM
participant "jeu:Jeu" as Jeu
participant "m:Personnage" as M
participant "c:Case" as C

Timer -> GM : evoluerMonster(commandeUser)
activate GM

GM -> Jeu : getMonstres()
activate Jeu
Jeu --> GM : listeMonstres
deactivate Jeu

alt listeMonstres non vide
	GM -> M : deplacer(jeu, commandeUser)
	activate M

	M -> Jeu : getSuivant(x, y, commandeUser)
	activate Jeu
	Jeu --> M : coord[]
	deactivate Jeu

	M -> Jeu : verifierDeplacement(coord[0], coord[1], commandeUser)

	M -> Jeu : getChar(coord[0], coord[1])
	activate Jeu
	Jeu --> M : typeCase
	deactivate Jeu

	alt case piege
		M -> Jeu : getCases()
		activate Jeu
		Jeu --> M : listeCases
		deactivate Jeu

		loop pour chaque case
			M -> C : getCoord()
			activate C
			C --> M : coordCase[]
			deactivate C

			alt coordCase[0] == coord[0] && coordCase[1] == coord[1]
                M -> C : effet(M)
                activate C
                C --> M
                deactivate C
            end
		end
		M -> M : setPos(coord[0], coord[1])
	else case vide ou fin
		M -> M : setPos(coord[0], coord[1])
	end
	
	M --> GM
	deactivate M
	
	GM -> GM : verifMort()
end

GM --> Timer
deactivate GM
@enduml