@startuml
title Fonctionnalité 9 - Déplacement aléatoire des monstres

actor Timer
participant "gestionnaireMonstres:gestionnaireMonstres" as GM
participant "jeu:Jeu" as Jeu
participant "c:Case" as C

Timer -> GM : evoluerMonster(commandeUser)
activate GM

GM -> Jeu : getMonstres()
activate Jeu
Jeu --> GM : listeMonstres
deactivate Jeu

alt listeMonstres non vide
	GM -> Jeu : getMonstres().size()
	activate Jeu
	Jeu --> GM : taille
	deactivate Jeu

	create "m:Personnage" as M
	GM -> M : listeMonstres.get(index)

	GM -> M : getX()
	activate M
	M --> GM : x
	deactivate M

	GM -> M : getY()
	activate M
	M --> GM : y
	deactivate M

	GM -> Jeu : getSuivant(x, y, commandeUser)
	activate Jeu
	Jeu --> GM : coord[]
	deactivate Jeu

	GM -> Jeu : verifierDeplacement(coord[0], coord[1], commandeUser)

	GM -> Jeu : getChar(coord[0], coord[1])
	activate Jeu
	Jeu --> GM : typeCase
	deactivate Jeu

	alt case piege
		GM -> Jeu : getCases()
		activate Jeu
		Jeu --> GM : listeCases
		deactivate Jeu

		loop pour chaque case
			GM -> C : getCoord()
			activate C
			C --> GM : coordCase[]
			deactivate C

			alt coordCase[0] == coord[0] && coordCase[1] == coord[1]
                GM -> C : effet(M)
                activate C
                C --> GM
                deactivate C
                GM -> GM : verifMort()
            end
		end
		GM -> M : setPos(coord[0], coord[1])
		activate M
		M --> GM
		deactivate M
	else case vide ou fin
		GM -> M : setPos(coord[0], coord[1])
		activate M
		M --> GM
		deactivate M
	end
end

GM --> Timer
deactivate GM

@enduml