@startuml
title Fonctionnalité 8 - Chargement de niveau (Monstres, cases, ...) depuis un fichier

participant "MainZeldiablo" as Main
participant "Chargement" as Chargement
participant "j:Jeu" as Jeu
participant "lab:Labyrinthe" as Laby

Main -> Chargement : chargerNiveau(j, nomFichier)
activate Chargement

Chargement -> Chargement : convertLab(nomFichier, ligne)
activate Chargement
create Laby
Chargement -> Laby : new Labyrinthe(max, ligne.size())
Chargement --> Chargement
deactivate Chargement

Chargement -> Jeu : getCases().clear()
Chargement -> Jeu : getMonstres().clear()

loop Pour chaque caractère du fichier (x, y)
    alt MUR ('#')
        Chargement -> Laby : addMur(x, y)
    else HERO ('P')
        create "hero:Aventurier" as Hero
        Chargement -> Hero : new Aventurier(x, y, 5)
    else PIEGE ('T')
        create "piege:Piege" as Piege
        Chargement -> Piege : new Piege(x, y)
        Chargement -> Jeu : getCases().add(piege)
    else MurFriable ('F')
        create "mur:MurFriable" as Mur
        Chargement -> Mur : new MurFriable(x, y)
        Chargement -> Jeu : getCases().add(mur)
    else MONSTRE ('M')
        create "m:Monstre" as Monstre
        Chargement -> Monstre : new Monstre(x, y, 3)
        Chargement -> Jeu : getMonstres().add(m)
    end
end

Chargement -> Jeu : setLaby(lab)
Chargement -> Jeu : setHero(hero)
Chargement -> Jeu : setFin(fin)

Chargement --> Main
deactivate Chargement
@enduml
