@startuml
title Fonctionnalité 2 — chargerJeu()

actor Joueur
participant "jeu:Jeu" as Jeu
participant "laby:Labyrinthe" as Laby

Joueur -> Jeu : chargerJeu(nomFichier)
activate Jeu

Jeu -> Jeu : convertLab(nomFichier, ligne)
create Laby
Jeu -> Laby : new Labyrinthe(max, ligne.size())

loop Pour chaque caractères du fichier
    alt MUR
        Jeu -> Laby : addMur(x, y)
        activate Laby
        Laby --> Jeu
        deactivate Laby
    else PJ
        create "hero:Aventurier" as Hero
        Jeu -> Hero : new Aventurier(x, y)
        Jeu -> Jeu : setPerso(hero)
    else VIDE
    else caractère inconnu
        Jeu -> Jeu : throw FichierIncorrectException("caractère inconnu")
    end
end

alt Aventurier absent
    Jeu -> Jeu : throw FichierIncorrectException("Aventurier absent")
end

Jeu -> Jeu : setLaby(laby)

Jeu --> Joueur
deactivate Jeu

@enduml