@startuml
title Fonctionnalité 1 — Déplacement de l'aventurier

actor Joueur
participant "j:Jeu" as Jeu
participant "laby:Labyrinthe" as Laby
participant "hero:Aventurier" as Hero

Joueur -> Jeu : deplacerHero(action)
activate Jeu

Jeu -> Jeu : getSuivant(action)
activate Jeu
Jeu --> Jeu :[x, y]
deactivate Jeu

Jeu -> Laby : getCase(x, y)
activate Laby
Laby --> Jeu : true / false
deactivate Laby

alt case traversable
    Jeu -> Hero : setPos(x, y)
    activate Hero
    Hero --> Jeu
    deactivate Hero
else mur ou hors limites
end

Jeu --> Joueur
deactivate Jeu

@enduml