@startuml
title Fonctionnalité 3 - Monstres incendiaires (Pose de Bombe)

participant "m : Artificier" as Artificier
participant "j : Jeu" as Jeu

activate Artificier

create "b : Bombe" as Bombe
Artificier -> Bombe : new Bombe(x, y)
activate Bombe
Bombe --> Artificier : b
deactivate Bombe

Artificier -> Jeu : addCase(b)
activate Jeu
Jeu --> Artificier
deactivate Jeu

Artificier -> Bombe : exploser(j)
activate Bombe
Bombe --> Artificier
deactivate Bombe

deactivate Artificier
@enduml
