@startuml
title Fonctionnalité 2 - Affichage visuel des attaques

participant "moteur : MoteurGraphique" as Moteur
participant "jeu : DessinLaby" as Dessin
participant "j : Jeu" as Jeu
participant "m : Personnage" as Monstre
participant "hero : Aventurier" as Hero

activate Moteur
Moteur -> Dessin : dessiner(im)
activate Dessin

Dessin -> Jeu : getMonstres()
activate Jeu
Jeu --> Dessin : monstres
deactivate Jeu

loop Pour chaque monstre m dans monstres
    Dessin -> Monstre : getIsAttaque()
    activate Monstre
    Monstre --> Dessin : true/false
    deactivate Monstre

    alt isAttaque == true
        Dessin -> Monstre : getType()
        activate Monstre
        Monstre --> Dessin : mtype
        deactivate Monstre
    else isAttaque == false
        Dessin -> Monstre : getType()
        activate Monstre
        Monstre --> Dessin : mtype
        deactivate Monstre
    end
end

Dessin -> Jeu : getHero()
activate Jeu
Jeu --> Dessin : hero
deactivate Jeu

Dessin -> Hero : getIsAttaque()
activate Hero
Hero --> Dessin : true/false
deactivate Hero

deactivate Dessin
deactivate Moteur
@enduml
