@startuml
title Fonctionnalité 1 - Mise en place de l'amulette

participant "Main : MainZeldiablo" as Main
participant "j : Jeu" as Jeu

activate Main
Main -> Jeu : "chargerNiveau("laby/niveaux/lvl1.txt")"
activate Jeu

alt Caractère lu est Jeu.AMULETTE ('A')
    create "amulette : Amulette" as Amulette
    Jeu -> Amulette : new Amulette(j, i)
    Jeu -> Jeu : cases.add(amulette)
end

Jeu --> Main
deactivate Jeu
deactivate Main
@enduml
