@startuml
title Fonctionnalité 3 - Fin du jeu : victoire du héros

participant "Main : MainZeldiablo" as Main
participant "j : Jeu" as Jeu
participant "hero : Aventurier" as Hero

activate Main
Main -> Jeu : etreFini()
activate Jeu

Jeu -> Hero : haveItem("Amulette")
activate Hero

loop Pour chaque Item o dans inventaire
    alt o.getType().equals("Amulette")
        Hero --> Jeu : true
    end
end
deactivate Hero

Jeu -> Hero : getX()
activate Hero
Hero --> Jeu : xHero
deactivate Hero

Jeu -> Hero : getY()
activate Hero
Hero --> Jeu : yHero
deactivate Hero

Jeu --> Main : true
deactivate Jeu
deactivate Main
@enduml
