@startuml
title Q5

'''classes
class Jeu
interface Personnage
class Aventurier
class Labyrinthe

'''relations
Jeu "1" --> "1" Labyrinthe : comporte
Jeu "1" --> "*" Personnage : gère
Personnage <|.. Aventurier
@enduml