@startuml
'''classes
class Jeu
interface Personnage
class Aventurier
class Labyrinthe

'''relations
Jeu "1" --> "1" Labyrinthe : comporte
Jeu "1" --> "1" Aventurier : gère
Personnage <|.. Aventurier
@enduml