@startuml
'https://plantuml.com/sequence-diagram


    MainZeldiablo  -> Chargement : chargerNiveaux()
    Activate Chargement

    create "hero:Aventurier" as Hero
    Chargement -> Hero : new Aventurier()

    Hero -> "<i> Personnage </i>" : etreMort()
    Activate "<i> Personnage </i>"




    alt this.pv > 1
      "<i> Personnage </i>" --> MainZeldiablo :true
    else
      "<i> Personnage </i>" --> MainZeldiablo :false
      deactivate "<i> Personnage </i>"
    end











@enduml