@startuml
    title Q5 - Diagramme de classe

class Jeu {
    -laby : Labyrinthe
    -hero : Aventurier
    -fin : int[]
    +BAS = "Bas" : static final String
    +GAUCHE = "Gauche" : static final String
    +DROITE = "Droite" : static final String

    +setHero(perso : Personnage) : void
    +getHero() : Personnage
    +getLaby() : Labyrinthe

    +chargerJeu(nomFichier : String) : void
    +convertLab(nomFichier : String, ligne : ArrayList<String>) : Labyrinthe
    +setLaby(laby : Labyrinthe) : void
    -getChar(x : int, y : int) : char
    +jeuToString() : String
    +{static} getSuivant(x : int, y : int, commandeUser : Commande) : int[]
    +deplacer(commandeUser : Commande) : void
}
class Labyrinthe {
    +MUR = '#' : static final char
    +HERO = '@' : static final char
    +FIN = '&' : static final char
    +VIDE = ' ' : static final char

    +Labyrinthe(x : int, y : int)
    +getCases(int x, int y) : int[][]
    +addMur(x : int, y : int) : void
    +verifierDeplacement(x : int, y : int, commandeUser : Commande) : void
    +etreFini() : boolean
}
interface Personnage {
    +getX() : int
    +getY() : int

    +setPos(x : int, y : int) : void
}
class Aventurier {
    -x : int
    -y : int

    +Aventurier(x : int, y : int) : void
    +getX() : int
    +getY() : int

    +setPos(x : int, y : int) : void

}
class FichierIncorrectException {
    +FichierIncorrectException(message : String) : void
}
interface DessinJeu {
    +{abstract} dessiner(image : BufferedImage) : void
}
class DessinLaby {
    -jeu : Jeu

    +DessinLaby(jeu Jeu) : void
    +dessiner(image : BufferedImage) : void
}

DessinJeu <|-- DessinLaby
DessinLaby "1" --> "1" Jeu : affiche
Jeu --> Labyrinthe
Jeu --> Aventurier
Personnage <|.. Aventurier
Jeu ..> FichierIncorrectException
@enduml